blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import posts.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(posts.urls, namespace='Post')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/posts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views

app_name = "posts"

urlpatterns = [
    path('', Index, name='Index'),
    path('detail/<int:pid>', detail, name='detail'),
    path('category/<int:cid>', category, name='category'),
    path('userposts/<int:uid>', userposts, name='userposts'),
    path('tag/<int:tid>', tag, name='tag'),
    path('login', Login, name='login'),
    path('register', Register, name='register'),
    path('logout', Logout, name='logout'),
    path('createpost', CreatePost, name='createpost'),
    path('updateblog/<int:bid>', UpdateBlog, name='updateblog'),
    path('deleteblog/<int:bid>', DeleteBlog, name='deleteblog'),
    path('likepost/<int:pid>', LikePost, name='like'),
    path('searchpost', SearchPost, name='searchpost'),
    path('updateProfile', UpdateProfile, name='updateprofile'),
    path('password_reset', PasswordReset, name="reset_password"),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('contact', contact, name='contact'),
    path('about', about, name='about'),
]

blog/posts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.



class User_Details(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    phone = models.TextField(max_length=10, null=True)
    image = models.FileField(null=True)
    about = models.TextField(null=True)

    def __str__(self):
        return self.usr.username

class Category(models.Model):
    title = models.CharField(max_length=150)

    def __str__(self):
        return self.title

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    publishing_date = models.DateTimeField(auto_now_add= True)
    image = models.FileField(null=True)
    User = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1, related_name="post")
    tag = models.ManyToManyField(Tag, related_name="posts", blank=True)
    likecount = models.IntegerField(default=0)
    commentcount = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class LikeComment(models.Model):
    post_data = models.ForeignKey(Post, on_delete=models.CASCADE,null=True)
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    like = models.BooleanField(default=False)

    def __str__(self):
        return self.post_data.title

class Comment(models.Model):
    post_data = models.ForeignKey(Post, on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    content = models.TextField()
    publishing_date = models.DateField(auto_now_add=True)



    def __str__(self):
        return self.post_data.title

blog/posts/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth import login, logout, authenticate
from datetime import date
from django.core.paginator import Paginator

# Create your views here.
def All_category():
    all_cat = Category.objects.all()
    li = []
    for i in all_cat:
        c = Post.objects.filter(category=i).count()
        li.append(c)
    z = zip(all_cat, li)
    return z


def tags():
    tags = Tag.objects.all()
    return tags


def recent_and_popular():
    allpost = Post.objects.all()

    recent_three = allpost[::-1][:3]
    popular_five = Post.objects.order_by('-likecount')[:4]
    return recent_three, popular_five


def Index(request):
    data = None
    if request.user.is_authenticated :
        data = User_Details.objects.filter(usr=request.user).first()
    post_data = Post.objects.all().order_by('-publishing_date')
    pg = Paginator(post_data, 5)
    page_number = request.GET.get('page')
    page_obj = pg.get_page(page_number)
    recent, popular = recent_and_popular()
    p = {"allcat": All_category(), 'listcat': All_category() ,'pg': pg ,'post': page_obj, "tags": tags(), "userdetail": data, "recent":recent, "popular":popular, "pg":pg}
    return render(request, 'posts/index.html', p)



def Register(request):
    already = False
    perror = False
    succ = False

    if request.method == 'POST':
        re = request.POST

        uname = re['username']
        fname = re['fname']
        lname = re['lname']
        p1 = re['p1']
        p2 = re['p2']
        if not request.FILES:
            pass
        else:
            img = request.FILES['img']

        data = User.objects.filter(username=uname)

        if p1 != p2:
            perror = True
        else:
            if data:
                already = True
            else:
                succ = True
                user = User.objects.create_user(username=uname, first_name=fname, last_name=lname, password=p1)
                usr = User_Details.objects.create(usr=user, image=img)
                login(request, user)
                return redirect('posts:Index')

    dic = {'already': already, 'succ': succ, 'pass': perror}
    return render(request, 'posts/register.html',dic)


def Login(request):
    error = False

    if request.method == 'POST':
        re = request.POST

        uname = re['username']
        p = re['p']

        user = authenticate(username=uname, password=p)
        if user:
            login(request, user)
            return redirect('posts:Index')
        else:
            error = True

    dic = {'error': error}
    return render(request, 'posts/login.html',dic)

def Logout(request):
    logout(request)
    return redirect('posts:login')

def detail(request, pid):
    post_data = Post.objects.get(id=pid)
    uid = post_data.User.id
    publisher = User.objects.get(id=uid)

    d =False
    if request.user.is_authenticated:
        data = LikeComment.objects.filter(usr=request.user, post_data=post_data).first()
    if request.user.is_authenticated and data:
        if data.like == True :
            d = True

    likecount = LikeComment.objects.filter(post_data=post_data, like=True).count()


    comments = Comment.objects.filter(post_data=post_data)

    previous = Post.objects.filter(id__lt=pid).order_by('id').first()
    next = Post.objects.filter(id__gt=pid).order_by('id').first()

    commentcount = Comment.objects.filter(post_data=post_data).count()
    p = {"allcat": All_category(), 'post': post_data, 'publisher':publisher, "tags": tags(), "like":d, "likecount":likecount, "commentcount":commentcount, "comments":comments ,"previous":previous, "next":next}

    if request.method == 'POST':
        re = request.POST

        name = re['name']
        email = re['email']
        content = re['content']
        td = date.today()

        l = Post.objects.get(id=pid)
        l.commentcount += 1
        l.save()
        comment = Comment.objects.create(post_data=post_data, name=name, email=email, content=content, publishing_date=td)
        return redirect('posts:detail', pid=pid)


    return render(request, 'posts/single-blog.html', p)

def category(request, cid):
    post_data = Post.objects.filter(category=cid).order_by('-publishing_date')
    pg = Paginator(post_data, 5)
    page_number = request.GET.get('page')
    page_obj = pg.get_page(page_number)
    cname = Category.objects.filter(id=cid).first().title
    p = {"allcat": All_category(), 'post':page_obj , 'pg':pg ,'category': cname, "tags": tags()}
    return render(request, 'posts/category.html', p)

def tag(request, tid):
    post_data = Post.objects.filter(tag=tid).order_by('-publishing_date')
    pg = Paginator(post_data, 5)
    page_number = request.GET.get('page')
    page_obj = pg.get_page(page_number)
    tname = Tag.objects.filter(id=tid).first().name
    p = {"allcat": All_category(), 'post': page_obj, 'pg': pg, 'tagname': tname, "tags": tags()}
    return render(request, 'posts/category.html', p)

def CreatePost(request):
    p = {"allcat": All_category()}

    if request.method == 'POST':
        re = request.POST

        title = re['title']
        content = re['content']
        tag = re['tag']
        cat = re['cat']
        img = request.FILES['img']

        tags = tag.split(",")
        cdata = Category.objects.get(id=cat)
        user = request.user
        td = date.today()

        for t in tags :
            texist = Tag.objects.filter(name=t).first()
            if not texist :
                Tag.objects.create(name=t)

        pid = Post.objects.create(category=cdata, User=user, title=title, content=content, image=img, publishing_date=td)

        for t in tags :
            tid = Tag.objects.filter(name=t).first().id
            Post.objects.get(title=pid).tag.add(tid)

        return redirect('posts:Index')

    return render(request, 'posts/createpost.html', p)


def SearchPost(request):
    query = request.GET.get("query")
    post_data =  Post.objects.filter(Q(title__icontains=query) |
                                   Q(content__icontains=query) |
                                   Q(tag__name__icontains=query)
                                  ).order_by('id').distinct()
    pg = Paginator(post_data, 4)
    page_number = request.GET.get('page')
    page_obj = pg.get_page(page_number)

    p = {"allcat": All_category(), 'post':page_obj , 'pg':pg , "tags": tags()}
    return render(request, 'posts/search.html',p)


def UpdateBlog(request, bid):
    blog = Post.objects.filter(id=bid).first()
    if request.method == "POST":
        dd = request.POST
        if dd['title'] == None:
            pass
        else:
            t = dd['title']
            blog.title = t
            blog.save()

        if dd['content'] == None:
            pass
        else:
            s = dd['content']
            blog.content = s
            blog.save()

        if not request.FILES:
            pass
        else:
            i = request.FILES['img']
            blog.image = i
            blog.save()

        cat = dd['cat']
        tag = dd['tag']
        tags = tag.split(",")
        cdata = Category.objects.get(id=cat)
        td = date.today()

        blog.category = cdata
        blog.publishing_date = td
        blog.save()

        for t in tags:
            texist = Tag.objects.filter(name=t).first()
            if not texist:
                Tag.objects.create(name=t)

        for t in tags :
            tid = Tag.objects.filter(name=t).first().id
            Post.objects.get(id=bid).tag.add(tid)

        return redirect('posts:Index')


    tags = blog.tag.all()
    s = ','.join([str(i) for i in tags])
    dic = {"allcat": All_category(), "blogdetails": blog, "tags" : s}
    return render(request, 'posts/updateblog.html', dic)

def DeleteBlog(request, bid) :
    blog = Post.objects.filter(id=bid).first()
    blog.delete()
    return redirect('posts:Index')


def LikePost(request, pid):
    if not request.user.is_authenticated:
        return redirect('posts:login')
    data = Post.objects.get(id = pid)
    data2 = LikeComment.objects.filter(usr=request.user, like=True, post_data=data)


    if not data2:
        LikeComment.objects.create(post_data=data, usr=request.user, like=True)
        l= Post.objects.get(id=pid)
        l.likecount+=1
        l.save()

        print(l)
        return redirect('posts:detail',pid= pid)
    else:
        return redirect('posts:detail',pid= pid)


def UpdateProfile(request):
    data = User_Details.objects.filter(usr=request.user).first()
    Userd = User.objects.get(username=request.user)

    if request.method == "POST":

        dd = request.POST
        if dd['uname'] == None:
            pass
        else:
            t = dd['uname']
            Userd.username = t
            Userd.save()

        if dd['fname'] == '':
            pass
        else:
            t = dd['fname']
            Userd.first_name = t
            Userd.save()

        if dd['lname'] == '':
            pass
        else:
            t = dd['lname']
            Userd.last_name = t
            Userd.save()

        if dd['email'] == '':
            pass
        else:
            t = dd['email']
            Userd.email = t
            Userd.save()

        if dd['phoneno'] == '':
            pass
        else:
            t = dd['phoneno']
            data.phone = t
            data.save()

        if dd['about'] == '':
            pass
        else:
            t = dd['about']
            data.about = t
            data.save()

        if not request.FILES :
            pass
        else:
            i = request.FILES['img']
            data.image = i
            data.save()

    d = {"allcat": All_category(), "userdata":data}
    return render(request, 'posts/profile.html', d)


def PasswordReset(request):
     error = False
     succ = False

     if request.method == 'POST':

blog/posts/templates/posts/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Login Template</title>
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'assets/css/login.css' %}">
</head>
<body>
  <main>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6 login-section-wrapper">

          <div class="login-wrapper my-auto">
            <h1 class="login-title">Log in</h1>
          {% if error == True %}
          <h6 style="color:red">Error !</h6>
          {% endif %}
            <form method="post">
              {% csrf_token %}
              <div class="form-group">
                <label for="email">Username</label>
                <input  name="username" id="email" class="form-control" placeholder="">
              </div>
              <div class="form-group mb-4">
                <label for="password">Password</label>
                <input type="password" name="p" id="password" class="form-control" placeholder="">
              </div>
              <input name="login" id="login" class="btn btn-block login-btn" type="submit" value="Login">
            </form>
            <a href="#!" class="forgot-password-link">Forgot password?</a>
            <p class="login-wrapper-footer-text">Don't have an account? <a href="{% url 'posts:register' %}" class="text-reset">Register here</a></p>
          </div>
        </div>
        <div class="col-sm-6 px-0 d-none d-sm-block">
          <img src="{% static 'assets/images/login.jpg' %}" alt="login image" class="login-img">
        </div>
      </div>
    </div>
  </main>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>

blog/posts/templates/posts/passchangesucc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

blog/posts/templates/posts/profile.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
         <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
        <title>Fantom Blog</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/lightbox/simpleLightbox.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/animate-css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/jquery-ui/jquery-ui.css' %}">
        <!-- main css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    </head>
    <body>

        <!--================Header Menu Area =================-->
         <header class="header_area">
            <div class="logo_part">
            	<div class="container">
            		<a class="logo" href="#"><img src= "{% static 'img/logo.png' %}" alt=""></a>
            	</div>
            </div>
			<div class="main_menu">
				<nav class="navbar navbar-expand-lg navbar-light">
					<div class="container">
						<!-- Brand and toggle get grouped for better mobile display -->
						<a class="navbar-brand logo_h" href="index.html"><img src= "{% static 'img/logo.png' %}" alt=""></a>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
							<ul class="nav navbar-nav menu_nav">
								<li class="nav-item active"><a class="nav-link" href="index.html">Home</a></li>
								<li class="nav-item"><a class="nav-link" href="category.html">Category</a></li>
								<li class="nav-item"><a class="nav-link" href="archive.html">Archive</a></li>
								<li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pages</a>
									<ul class="dropdown-menu">
										<li class="nav-item"><a class="nav-link" href="single-blog.html">Blog Details</a></li>
										<li class="nav-item"><a class="nav-link" href="elements.html">Elements</a></li>
									</ul>
								</li>
								<li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
							</ul>
							<ul class="nav navbar-nav navbar-right ml-auto">
								<li class="nav-item"><a href="#" class="search"><i class="lnr lnr-magnifier"></i></a></li>
							</ul>
						</div>
					</div>
				</nav>
			</div>
        </header>
        <!--================Header Menu Area =================-->

        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Blog Post Details</h2>
						<div class="page_link">
							<a href="index.html">Home</a>
							<a href="single-blog.html">Post Details</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->

        <!--================Blog Area =================-->
        <section class="blog_area p_120 single-post-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="blog_right_sidebar">
                            <aside class="single_sidebar_widget author_widget">
                                {% if userdata.image %}
                                <img class="author_img rounded-circle" style="height:7rem; width:7rem" src="{{ userdata.image.url }}" alt="">
                                {% endif %}
                                <h4>{{ request.user.username }}</h4>
                                <p>{{ request.user.first_name }} {{ request.user.last_name }}</p>
                                 <div class="br"></div>
                                <h4>About</h4>
                                <p>{{ userdata.about }}</p>

                            </aside>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="comment-form mt-0 pt-2">
                            <h4>Update Profile</h4>
                          <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                                  <div class="form-group">
                                      <label>User Name:</label>
                                    <input type="text" name="uname" class="form-control" value="{{ request.user.username }}"   >
                                  </div>

                                 <div class="form-group">
                                     <label>First Name:</label>
                                    <input type="text" name="fname" class="form-control" value="{{ request.user.first_name }}"  >
                                  </div>
                                 <div class="form-group">
                                     <label>Last Name:</label>
                                    <input type="text" name="lname" class="form-control" value="{{ request.user.last_name }}"   >
                                  </div>
                                  <div class="form-group">
                                      <label>Email:</label>
                                    <input type="text" name="email" class="form-control" value="{{ request.user.email }}"  >
                                  </div>
                                 <div class="form-group">
                                     <label>Phone No:</label>
                                    <input type="text" name="phoneno" class="form-control" value="{{ userdata.phone }}"   >
                                  </div>
                                  <div class="form-group">
                                       <label>About</label>
                                   <textarea class="form-control mb-10" rows="5" name="about" value="{{ userdata.about }}" ></textarea>
                                  </div>


                                <div class="form-group">
                                    <input type="file" class="form-control  mt-4" name="img"  >
                                </div>

                               <input type="submit" class="primary-btn submit_btn"  placeholder="Title" value="Update Profile" >

                            </form>
                        </div>
        			</div>

                </div>
            </div>
        </section>
        <!--================Blog Area =================-->

        <!--================ start footer Area  =================-->
       <footer class="footer-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3  col-md-6 col-sm-6">
                        <div class="single-footer-widget">
                            <h6 class="footer_title">About Us</h6>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="single-footer-widget">
                            <h6 class="footer_title">Newsletter</h6>
                            <p>Stay updated with our latest trends</p>
                            <div id="mc_embed_signup">
                                <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative">
                                    <div class="input-group d-flex flex-row">
                                        <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
                                        <button class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>
                                    </div>
                                    <div class="mt-10 info"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="single-footer-widget instafeed">
                            <h6 class="footer_title">Instagram Feed</h6>
                            <ul class="list instafeed d-flex flex-wrap">
                                <li><img src= "{% static 'img/instagram/Image-01.jpg' %}" alt=""></li>
                                <li><img src= "{% static 'img/instagram/Image-02.jpg' %}" alt=""></li>
                                <li><img src= "{% static 'img/instagram/Image-03.jpg' %}" alt=""></li>
                                <li><img src= "{% static 'img/instagram/Image-04.jpg' %}" alt=""></li>
                                <li><img src= "{% static 'img/instagram/Image-05.jpg' %}" alt=""></li>
                                <li><img src= "{% static 'img/instagram/Image-06.jpg' %}" alt=""></li>
                                <li><img src= "{% static 'img/instagram/Image-07.jpg' %}" alt=""></li>
                                <li><img src= "{% static 'img/instagram/Image-08.jpg' %}" alt=""></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-6 col-sm-6">
                        <div class="single-footer-widget f_social_wd">
                            <h6 class="footer_title">Follow Us</h6>
                            <p>Let us be social</p>
                            <div class="f_social">
                            	<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-behance"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row footer-bottom d-flex justify-content-between align-items-center">
                    <p class="col-lg-12 footer-text text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                </div>
            </div>
        </footer>
		<!--================ End footer Area  =================-->




        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/stellar.js' %}"></script>
        <script src="{% static 'vendors/lightbox/simpleLightbox.min.js' %}"></script>
        <script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/isotope-min.js' %}"></script>
        <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'vendors/jquery-ui/jquery-ui.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'js/mail-script.js' %}"></script>
        <script src="{% static 'js/theme.js' %}"></script>
    </body>
</html>